### ISSUE TITLE
in callback catch

### ISSUE THREAD

**Issue by raichu** [JuliaOpt/NLopt.jl#15]
Using `:LN_COBYLA`, I'm getting a bunch of "in callback catch" errors (about 1300 times).

What I basically do is
```
opt = Opt(:LN_COBYLA, n)
lower_bounds!(opt, lb)
upper_bounds!(opt, ub)
xtol_rel!(opt,1e-4)

min_objective!(opt, myfunc)

(min,datamin,result) = optimize(opt, data)
```

Strangely, myfunc never gets called.

(lb, ub, data are all Array{Float64,1} of length n and n is 200)

**Comment by pjervis** [comment]
Hi, I'm having a similar problem, any ideas??? Thanks a lot!

Error: in callback catch
LoadError("C:/Users/pamela_j/Dropbox/PFunction/Programs/UKF_wox/Main_Est.jl",136,MethodError(zero,(Any,)))

Here is my code- line 136 is (minf,minx,ret) = optimize!(opt, param_start[:])-
#L=Likelihood(param_start,lambda,var_me,mu,k,DataRawt0,DataRawt1)
count = 0 # keep track of # function evaluations


# OPTIMIZATION

sig_lb=[0.3*ones(ntheta1,1), -1*ones(10,1)]
sig_ub=[1.7*ones(ntheta1,1), 1*ones(10,1)]

n_p=size(param_start,1)
l_b=[0.2, 0.001, 0.001, 0.001,0.001, -1.5,0.001, 0.2, 0.001, 0.001,0.001,-1.,0.02,0.02,0.2,ones(ntheta1,1)*-0.2,ones(ntheta1,1)*-0.2,sig_lb]
u_b=[0.99,  0.5,   0.5,   0.5, 0.5,  0.7,  0.5, 0.99, 0.5, 0.5,0.5,0.7,0.5,0.5,0.8,ones(ntheta1,1)*0.2,ones(ntheta1,1)*0.2,sig_ub]
opt = Opt(:LN_COBYLA, n_p)
lower_bounds!(opt, l_b[:])
lower_bounds(opt)
upper_bounds!(opt, u_b[:])
upper_bounds(opt)
xtol_rel!(opt,1e-4)
xtol_rel(opt)

max_objective!(opt, Obj_fun)
equality_constraint!(opt, (x,g) -> const1(x,g,1), 1e-8)
equality_constraint!(opt, (x,g) -> const2(x,g,1), 1e-8)

(minf,minx,ret) = optimize!(opt, param_start[:])
println("got $minf at $minx after $count iterations (returned $ret)")

**Comment by stevengj** [comment]
@pjervis, presumably you have a bug in your `Obj_fun` that is causing it to throw `MethodError(zero,(Any,))` (i.e. you are calling `zero(Any)`, probably implicitly via `sum` of an `Any[...]` array or similar, and no such method exists).

**Comment by pjervis** [comment]
@stevengj thanks for your answer! I think that I figure it out. I think that the problem is that I cannot calculate the variance: I define my data: Data1=Data[:,1:4] (6063x4 Array{Any,2}:) and then when I want to calculate the var(Data1[:,1]) I get "MethodError(zero,(Any,))". I tried also in a basic way too and I have the same problem: test = Any[1,2,3] then var(test) and I get the same error!!!

Also, I am not getting this message when I run my program in Mac using JuliaStudio, only when I use Windows, and I need windows because I want to use HPC...

Thanks a lot for your help!

**Comment by stevengj** [comment]
The fact that `var` does not work for `Any` arrays is a problem with Julia, and I've filed an issue (linked above).

In the meantime, the right thing is not to use `Any` arrays.   Using `Any` arrays is not a good idea anyway because they kill performance in Julia (since `Any` defeats type-inference, code manipulating `Any` values cannot be compiled to fast code).
