### ISSUE TITLE
from direct to stogo -> NLOPT_INVALID_ARGS

### ISSUE THREAD

**Issue by UnixJunkie** [JuliaOpt/NLopt.jl#200]
If I switch from direct to stogo for global optimization, I get this error.
With direct, the optimization is going on (but I guess it would work way
better if I exploit the gradient, hence the trial switch to stogo).

**Comment by odow** [comment]
Do you have a reproducible example? I don't fully understand what you mean.

**Comment by UnixJunkie** [comment]
No, I don't have a minimal example (way too much work to get one).
I have a problem where direct works; if I change the algorithm from direct to stogo, I get this error.

**Comment by odow** [comment]
Do you have constraints? stogo does not support constraints other than bound constraints.

**Comment by UnixJunkie** [comment]
I only have bound constraints.

**Comment by odow** [comment]
From the documentation: https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#error-codes-negative-return-values

`NLOPT_INVALID_ARGS` happens because "Invalid arguments (e.g. lower bounds are bigger than upper bounds, an unknown algorithm was specified, etcetera)."

It's impossible to say what the problem is without a reproducible example, so I'm going to close this issue. If you're still experiencing an issue and you have a reproducible example, please comment below and I will reopen the issue.
