### ISSUE TITLE
Complex number Optimization

### ISSUE THREAD

**Issue by fravals** [JuliaOpt/NLopt.jl#30]
Hi,
is it already implemented a optimization method for functions with complex number?

Using ``` :LN_COBYLA ``` with  a derivative free optimization I get this error

``` julia
in callback catch

type: Complex: in T, expected T<:Real, got Type{Any}
while loading In[15], in expression starting on line 15

 in CF_SVj at In[3]:9
```

as the function ```CF_SVj``` returns complex values.

Thanks

**Comment by stevengj** [comment]
It's not meaningful to optimize an objective that returns complex values, because complex values [are not ordered](https://en.wikipedia.org/wiki/Complex_number#Ordering).  For the same reason, you can't have complex inequality constraints.

You can have complex equality constraints, of course, but you should implement this as a vector-valued equality constraint that returns a vector `[real(c), imag(c)]`.

**Comment by mlubin** [comment]
Nothing to address in NLopt here.
