### ISSUE TITLE
Order of calls to target function and constraints

### ISSUE THREAD

**Issue by fredRos** [JuliaOpt/NLopt.jl#61]
I suppose my problem is one of nlopt itself rather than the julia interface but I'm not sure, so I post it here. I use COBYLA on a function `f` with two nonlinear constraints `g,h`. `f` is expensive to evaluate but the constraints are cheap. If the constraint is violated there is no point of evaluating `f`. My constraints prevent *unphysical values* leading to
```
ERROR: DomainError:
```
 in `f`.

 Is there any way to have the constraints evaluate first? I traced the calls and right now the order is `f,g,h` but I'd prefer `g,h,f`. The error message without a line specifying the source of the error was not very helpful.

**Comment by stevengj** [comment]
This has to be changed in the C library, and unfortunately every optimization algorithm in NLopt is potentially different.   e.g. COBLYA is derived from some Fortran code by Powell.

**Comment by stevengj** [comment]
If your constraints are cheap, of course, you could just evaluate them twice (once in the objective function).

Also, note that nlopt does not guarantee that the objective function is not evaluated outside the feasible set when you have nonlinear constraints.   On the other hand, it *does* guarantee that the objective function is never evaluated outside of the box constraints (lower/upper bounds on the design variables).   If possible, I would strongly suggest that you think about reformulating your degrees of freedom so that the "physical" constraints that lead to domain errors can be reformulated as box constraints.

**Comment by stevengj** [comment]
(An optimization algorithm like COBYLA actually uses values of your objective function outside of the feasible region to help it build up an affine approximation of your function, so it implicitly assumes that your function is defined and differentiable everywhere within the box constraints, even if they violate your nonlinear constraints.  If your function does not have this property, COBLYA is not going to perform well in any case.)

**Comment by fredRos** [comment]
I understand, thanks for clarification. Unfortunately the constraint is not simple enough to transform analytically so I will have to put up with poor performance.
